name: Publish to TestFlight
on: 
  push:
    branches:
      - 'feature/ci-cd'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    # - uses: actions/cache@v2
    #   with:
    #     path: Pods
    #     key: ${{ runner.os }}-pods-${{ hashFiles('Podfile.lock')}}
    #     restore-keys: |
    #       ${{ runner.os }}-pods-
    
    - name: Install Pods
      run: pod install
    - name: Build IOS App
      uses: yukiarrr/ios-build-action@v1.5.0
      with:
        project-path: VideoSDK.xcodeproj
        p12-base64: ${{ secrets.P12_BASE64 }}
        mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
        code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
        team-id: ${{ secrets.TEAM_ID }}
        certificate-password: ${{ secrets.CERTIFICATE_PASSWORD}}
        workspace-path: VideoSDK.xcworkspace # optional
        # export-options: ExportOptions.plist
        destinaition: ""

#     - name: 'Upload app to TestFlight'
#       uses: apple-actions/upload-testflight-build@v1
#       with:
#         app-path: 'output.ipa'
#         issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
#         api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
#         api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
